AllCops:
  NewCops: enable  
  TargetRubyVersion: 3.2
  SuggestExtensions: false
  
# Load Rails and RSpec extensions
require:
  - rubocop-rails
  - rubocop-rspec

# Disable rules you don't want
Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

#  style preferences
Style/StringLiterals:
  EnforcedStyle: double_quotes 

Layout/LineLength:
  Max: 120
  Enabled: true

Lint/RedundantCopEnableDirective:
  Enabled: false
